config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" } do
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :clients do
    resources :postings
  end

  resources :workers do
    resources :postings
  end

  resources :categories

  

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_and_belongs_to_many :postings

  self.inheritance_column = 'sti_type'
end

app/models/posting.rb
class Posting < ActiveRecord::Base
	belongs_to :user
	has_and_belongs_to_many :categories
end

app/models/user.rb
class User < ActiveRecord::Base

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  has_many :postings
  has_and_belongs_to_many :categories
  accepts_nested_attributes_for :categories
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :omniauthable, :omniauth_providers => [:facebook]
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

	def self.new_with_session(params, session)
		super.tap do |user|
		 if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
		   user.email = data["email"] if user.email.blank?
		 end
		end
	end

  enum role: [:client, :worker, :admin]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def show
		@categories = Category.all
		@category = Category.find(params[:id])
	end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
	before_action :authenticate_user!
	def index

		if current_user.client?
				@categories = Category.all
				@user = current_user
		elsif current_user.worker?
			redirect_to :root, alert: "You don't have permission to access this page."
		end
	end
end

app/controllers/postings_controller.rb
class PostingsController < ApplicationController
	  before_action :authenticate_user!
	def index
		@user = current_user
		@postings = Posting.all.order(:created_at)
	end

	def new
		@user = current_user
		@client = User.find(params[:client_id])
		@posting = @client.postings.build
	end
	
	def create
		@user = current_user
		@posting = current_user.postings.build(posting_params)
		categories = params[:posting][:category_ids]
		categories.pop
		categories.each do |category_id|
		   @posting.categories << Category.find(category_id.to_i)
		end
		if @posting.save
			redirect_to client_posting_path(current_user, @posting)
		else
			render :new
		end
	end

	def show
		@user = current_user
		@posting = Posting.find(params[:id])
	end

	# def show_category
	# 	@user = current_user
	# 	@categories = Category.find(params[:id])
	# 	@posting = Posting
	# end

	def edit
		@user = current_user
		@client = User.find(params[:client_id])
		@posting = Posting.find(params[:id])

	end

	def update
		@user = current_user
		@posting = Posting.find(params[:id])

		categories = params[:posting][:category_ids]
		categories.pop
		categories.each do |k|
		   @posting.categories << Category.find(k.to_i)
		end

		if @posting.update(posting_params)
			redirect_to client_posting_path(current_user,@posting)
		else
			render :edit
		end
	end

	def destroy
		@posting = Posting.find(params[:id])
		@posting.destroy
		redirect_to client_postings_path
	end

	private
	def posting_params
		params.require(:posting).permit(:title,:description,:date,:compensation,:phone,:email)
	end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def new
    super
  end

  def create
    @user = User.new(user_params)
    if @user.save
    	sign_in_and_redirect(@user)
    else
    	redirect_to root_path
    end
  end

  def update
    super
  end
  def after_sign_up_path_for(resource)
    '/'
  end
  private
  def user_params
  	params.require(:user).permit(:name, :email, :password, :password_confirmation, :phone, :description, :role, :avatar)
  end
end 

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
	def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  	if current_user.client?
  		redirect_to clients_path
  	elsif current_user.worker?
  		redirect_to workers_path
  	end
  end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
	  before_action :authenticate_user!
	def index
		if current_user.worker?
			@categories = Category.all
			@user = current_user
		elsif current_user.client?
			redirect_to :root, alert: "You don't have permission to access this page."
		end
	end

	def show
			@user = User.find(params[:id])
			# @category = Category.find(params[:category_id])
	end

	def edit
		if current_user.worker?
		@worker = current_user
		@categories = Category.all
		elsif current_user.client?
			redirect_to :root, alert: "You don't have permission to access this page."
		end
	end

	def update

		if current_user.worker?

		@worker = current_user
		@worker.update(worker_params)
		worker_categories = params[:user][:user][:category_ids]
		worker_categories.pop
		@worker.categories = []
		worker_categories.each do |category_id|
			@worker.categories << Category.find(category_id.to_i)
		end
		@worker.save
		redirect_to worker_path @worker

		elsif current_user.client?
			redirect_to :root, alert: "You don't have permission to access this page."
		end

	end

	private
	def worker_params
		params.require(:user).permit(:name,:description,:email,:phone,:email, :role, :avatar)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/postings_helper.rb
module PostingsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_navbarclient.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class ="logo"> <%= link_to image_tag("logo.png"), welcome_index_path%>
    </div>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li>
        <%= link_to 'All postings', client_postings_path(current_user,@posting) %>
        </li>
        <li>
        <%= link_to 'New Posting', new_client_posting_path(current_user,@posting)%>
        </li>
      </ul>
          <p class="navbar-text pull-right">
          <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>.
            <%= link_to 'Edit account', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% end %>
    </div>
  </div>
</nav>

app/views/categories/_navbarworker.html.erb
</nav>
</div>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class ="logo"> <%= link_to image_tag("logo.png"), welcome_index_path%>
    </div>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li>
        <%= link_to 'View Profile', worker_path(current_user) %>
        </li>
      </ul>
          <p class="navbar-text pull-right">
          <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>.
            <%= link_to 'Edit account', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% end %>
    </div>
  </div>
</nav>

app/views/categories/show.html.erb
<% if current_user.worker? %>

<%= render 'navbarworker' %>

	<h1><%= @category.type %> Job Postings</h1>
	<div class="form">
	<% @category.postings.each do |posting| %>
		<div class="display"><%= link_to posting.title, client_posting_path(current_user,posting) %></p></div>
	<% end %>
	</div>

<% elsif current_user.client? %>

<%= render 'navbarclient' %>

	<h1><%= @category.type %>s</h1>
	<div class="form">
		<% @category.users.worker.each do |worker| %>
			<div class="display"><%= link_to worker.name, worker_path(worker, category_id: @category.id) %></div>
		<% end %>
</div>
<% end %>

app/views/clients/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class ="logo"> <%= link_to image_tag("logo.png"), welcome_index_path%>
    </div>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li>
        <%= link_to 'Your Postings', client_postings_path(current_user,@posting) %>
        </li>
        <li>
        <%= link_to 'New Posting', new_client_posting_path(current_user,@posting)%>
        </li>
      </ul>
          <p class="navbar-text pull-right">
          <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>.
            <%= link_to 'Edit account', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% end %>
    </div>
  </div>
</nav>

app/views/clients/index.html.erb
<%= render 'navbar' %>

<div class= "greeter"><h2>Hello <%= @user.name %>!</h2></div>

<body>
    <!-- Page Content -->
    <div class="container">

        <!-- Page Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Workers
                    <small>by category</small>
                </h1>
            </div>
        </div>
        <!-- /.row -->

        <!-- Projects Row -->
        <div class="row">
        <% @categories.each do |category| %>
	          <div class="col-md-3 portfolio-item">
		          	<%= link_to category_path(category) do %>
		          		<%= category.type %> <br/>
		          		<i class="fa fa-<%= category.icon %> fa-5x"></i>
		          	<% end %>
	          </div>
				<% end %>
        </div>

        <hr>
  
      <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Bridge 2015</p>
                </div>
            </div>
            <!-- /.row -->
        </footer>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bridge</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Syncopate' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Poppins:400,700' rel='stylesheet' type='text/css'>
</head>
<body>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/postings/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class ="logo"> <%= link_to image_tag("logo.png"), welcome_index_path%>
    </div>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li>
        <%= link_to 'Your Postings', client_postings_path(current_user,@posting) %>
        </li>
        <li>
        <%= link_to 'New Posting', new_client_posting_path(current_user,@posting)%>
        </li>
      </ul>
          <p class="navbar-text pull-right">
          <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>.
            <%= link_to 'Edit account', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% end %>
    </div>
  </div>
</nav>

app/views/postings/_navbarworker.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class ="logo"> <%= link_to image_tag("logo.png"), welcome_index_path%>
    </div>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li>
        <%= link_to 'View Profile', worker_path(current_user) %>
        </li>
      </ul>
          <p class="navbar-text pull-right">
          <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>.
            <%= link_to 'Edit account', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% end %>
    </div>
  </div>
</nav>

app/views/postings/edit.html.erb
<%= render 'navbar' %>

<div class= form> 
<h1> Edit Job Post </h1>

<%= simple_form_for [@client, @posting], url: client_posting_path(current_user,@posting) do |f| %>

<% if @posting.errors.any? %>
<h3>
<%= pluralize(@posting.errors.count, "error") %>
This posting could not be saved
</h3>
<ul>
<% @posting.errors.full_messages each do |message| %>
<li><%= message %></li>
</ul>

<% end %>
<% end %>

</br>
</br>

<p>
	<div class="form-inputs">
	<%= f.input :title %>
	<%= f.association :categories, as: :check_boxes, label_method: :type %>
	<%= f.input :description %>
  	<%= f.input :date %>
  	<%= f.input :compensation, placeholder: "Ex. R100/hour or R500/service" %>
  	<%= f.input :phone %>
  	<%= f.input :email %>
  	</div>
  	<%= f.button :submit %>
</p>

<% end %>
 
<%= link_to 'Back', client_postings_path(current_user, @posting) %>
</div>

app/views/postings/index.html.erb
<%= render 'navbar' %>

<h1>Postings</h1>
<div class="form">
<% @postings.each do |posting|%>

<% if current_user.id == posting.user_id %>
<div class="display"><%= link_to posting.title, client_posting_path(current_user, posting) %>
<p><%= posting.description %></p></div>
<% end %>
<% end %>
</div>

app/views/postings/new.html.erb
<%= render 'navbar' %>

<div class= form> 
<h1> New Job Post </h1>


<%= simple_form_for [@client, @posting], url: client_postings_path(@client) do |f| %>

<% if @posting.errors.any? %>
<h3>
<%= pluralize(@posting.errors.count, "error") %>
This posting could not be saved
</h3>
<ul>
<% @posting.errors.full_messages each do |message| %>
<li><%= message %></li>
</ul>

<% end %>
<% end %>

</br>
</br>

<p>
	<div class="form-inputs">
	<%= f.input :title %>
	<%= f.association :categories, as: :check_boxes, label_method: :type %>
	<%= f.input :description %>
  	<%= f.input :date %>
  	<%= f.input :compensation, placeholder: "Ex. R100/hour or R500/service" %>
  	<%= f.input :phone %>
  	<%= f.input :email %>
  	</div>
  	<%= f.button :submit %>
</p>

<% end %>


</div>

app/views/postings/show.html.erb
<% if current_user.client? %>
	<%= render 'navbar' %>
<% elsif current_user.worker? %>
	<%= render 'navbarworker' %>
<% end %>


<h1><%= @posting.title %></h1>

<div class="form">

<div class="form-inputs"
<p><strong>Categories:</strong></p> <% @posting.categories.each do |category| %><p><%= category.type %></p><% end %>

<p><strong> Description: </strong><%= @posting.description %></p>
<p><strong> Date&Time: </strong><%= @posting.date %></p>
<p><strong> Compensation: </strong><%= @posting.compensation %></p>
<p><strong> Phone number: </strong><%= @posting.phone %></p>
<p><strong> Contact email: </strong><%= @posting.email %></p>
</br>

</div>

<% if current_user.client? %>
<%= link_to 'Edit', edit_client_posting_path(current_user, @posting) %> |
<%= link_to 'Delete', client_posting_path(current_user, @posting),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
<% end %>

</div>

app/views/welcome/index.html.erb
<h1>Welcome index</h1>

app/views/workers/_navbar.html.erb
</nav>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class ="logo"> <%= link_to image_tag("logo.png"), welcome_index_path%>
    </div>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li>
        <%= link_to 'View Profile', worker_path(current_user) %>
        </li>
      </ul>
          <p class="navbar-text pull-right">
          <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>.
            <%= link_to 'Edit account', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% end %>
    </div>
  </div>
</nav>

app/views/workers/_navbarclient.html.erb
</nav>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class ="logo"> <%= link_to image_tag("logo.png"), welcome_index_path%>
    </div>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li>
        <%= link_to 'Your Postings', client_postings_path(current_user,@posting) %>
        </li>
        <li>
        <%= link_to 'New Posting', new_client_posting_path(current_user,@posting)%>
        </li>
      </ul>
          <p class="navbar-text pull-right">
          <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>.
            <%= link_to 'Edit account', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% end %>
    </div>
  </div>
</nav>

app/views/workers/edit.html.erb
<%= render 'navbar' %>

<h1>Edit Profile</h1>
<div class ="form">

<%= simple_form_for @worker, url: worker_path(@worker), method: :patch do |f| %>

<% if @worker.errors.any? %>
<h3>
<%= pluralize(@worker.errors.count, "error") %>
This worker could not be saved
</h3>
<ul>
<% @worker.errors.full_messages each do |message| %>
<li><%= message %></li>
</ul>

<% end %>
<% end %>

</br>
</br>

<p>
	<div class="form-inputs">
	 <%= f.input :name, required: true %>
    <%= f.input :email, required: true, autofocus: true %>
    <%= f.simple_fields_for @worker do |c| %>  
       <%= c.association :categories, as: :check_boxes, label_method: :type %>
    <% end %>
    <%= f.input :description, label: "Describe services provided" %>
    <%= f.input :phone, label: "Contact number" %>
    <%= f.input :avatar, label: "Upload photo", as: :file %>
  	</div>
  	<%= f.button :submit %>
</p>
<% end %>
</div>

app/views/workers/index.html.erb
<%= render 'navbar' %>

<div class="greeter"><h2>Hello <%= @user.name %>!</h2></div>

<body>
    <!-- Page Content -->
    <div class="container">

        <!-- Page Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Job Postings
                    <small>by category</small>
                </h1>
            </div>
        </div>
        <!-- /.row -->

        <!-- Projects Row -->
        <div class="row">
        <% @categories.each do |category| %>
	          <div class="col-md-3 portfolio-item">
		          	<%= link_to category_path(category) do %>
		          		<%= category.type %> <br/>
		          		<i class="fa fa-<%= category.icon %> fa-5x"></i> 
		          	<% end %>
	          </div>
				<% end %>
        </div>

        <hr>
  
      <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Bridge 2015</p>
                </div>
            </div>
            <!-- /.row -->
        </footer>
</body>

app/views/workers/show.html.erb
<h1><%=@user.name%>'s Profile</h1>

<% if current_user.worker? %>
	<%= render 'navbar' %>
<% elsif current_user.client?%>
	<%= render 'navbarclient' %>
<% end %>
	

<div class= "show">

<p><strong><%= image_tag @user.avatar.url(:medium) %></strong></p>
<div class="form-inputs">
<p><strong>Categories:</strong></p> <% @user.categories.each do |category| %><li><%= category.type %></li><% end %> <br/>

<p><strong> Description: </strong><%= @user.description %></p>
<p><strong> Phone number: </strong><%= @user.phone %></p>
<p><strong> Contact email: </strong><%= @user.email %></p>
</br>
</div>

<% if current_user.worker? %>
<%= link_to 'Edit', edit_worker_path(current_user) %>
<% end %>
</div>